/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profileCompletion' : IDL.Nat,
  'earnings' : IDL.Nat,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const Badge = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'postId' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'completedCourses' : IDL.Nat,
  'productsListed' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'communityPosts' : IDL.Nat,
  'enrolledCourses' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addCourse' : IDL.Func([IDL.Text, Course], [], []),
  'addProduct' : IDL.Func([IDL.Text, Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'createProfile' : IDL.Func([Profile], [], []),
  'enrollInCourse' : IDL.Func([IDL.Text], [], []),
  'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCoursesByTitle' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostsByAuthor' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsBySeller' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'updateCourseProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profileCompletion' : IDL.Nat,
    'earnings' : IDL.Nat,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const Badge = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'postId' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'completedCourses' : IDL.Nat,
    'productsListed' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'communityPosts' : IDL.Nat,
    'enrolledCourses' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addCourse' : IDL.Func([IDL.Text, Course], [], []),
    'addProduct' : IDL.Func([IDL.Text, Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'createProfile' : IDL.Func([Profile], [], []),
    'enrollInCourse' : IDL.Func([IDL.Text], [], []),
    'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCoursesByTitle' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostsByAuthor' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsBySeller' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'updateCourseProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };