/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface Comment {
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'postId' : string,
}
export interface Course {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'description' : string,
  'category' : string,
}
export interface DashboardStats {
  'completedCourses' : bigint,
  'productsListed' : bigint,
  'totalEarnings' : bigint,
  'communityPosts' : bigint,
  'enrolledCourses' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Post {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'likes' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface Product {
  'id' : string,
  'title' : string,
  'description' : string,
  'seller' : Principal,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface Profile {
  'bio' : string,
  'name' : string,
  'profileCompletion' : bigint,
  'earnings' : bigint,
  'profilePicture' : [] | [ExternalBlob],
  'skills' : Array<string>,
  'location' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'addCourse' : ActorMethod<[string, Course], undefined>,
  'addProduct' : ActorMethod<[string, Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'createProfile' : ActorMethod<[Profile], undefined>,
  'enrollInCourse' : ActorMethod<[string], undefined>,
  'getBadges' : ActorMethod<[], Array<Badge>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getCoursesByTitle' : ActorMethod<[], Array<Course>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getPostsByAuthor' : ActorMethod<[], Array<Post>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getProductsBySeller' : ActorMethod<[], Array<Product>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'updateCourseProgress' : ActorMethod<[string, bigint], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];